Add tests
vitalik33811/SauceDemo pull request #1
Opened 2021-11-02 15:47 UTC by vitalik33811

2021-11-03 16:25 UTC, vchesnakoutest requested changes

2021-11-03 16:25 UTC, vchesnakoutest commented on src/main/java/pages/BasePage.java
> +
пустые строки удаляй, проверь в остальных местах тоже

2021-11-03 16:25 UTC, vchesnakoutest commented on src/main/java/pages/CartPage.java
> +    public void setCheckoutButton(){
clickCheckoutButton

2021-11-03 16:25 UTC, vchesnakoutest commented on src/main/java/pages/CheckoutCompletePage.java
> +    public String setCheckoutCompleteTitle(){
getCheckoutCompleteTitleText

2021-11-03 16:25 UTC, vchesnakoutest commented on src/main/java/pages/CheckoutStepOnePage.java
> +    public void setContinueButton() {
clickContinueButton

2021-11-03 16:25 UTC, vchesnakoutest commented on src/main/java/pages/CheckoutStepOnePage.java
> +    public String setErrorMessageCheckoutLastName() {
getErrorMessageCheckoutLastNameText

2021-11-03 16:25 UTC, vchesnakoutest commented on src/main/java/pages/CheckoutStepOnePage.java
> +    public String setErrorMessageCheckoutFirstName() {
изменить название метода по аналогии

2021-11-03 16:25 UTC, vchesnakoutest commented on src/main/java/pages/CheckoutStepTwoPage.java
> +    private static final By CHECKOUT_2_FINISH_BUTTON = By.xpath("//*[@id='finish']");
можно просто CHECKOUT_FINISH_BUTTON

2021-11-03 16:25 UTC, vchesnakoutest commented on src/main/java/pages/CheckoutStepTwoPage.java
> +    public void setCheckout2FinishButton(){
clickCheckoutFinishButton

2021-11-03 16:25 UTC, vchesnakoutest commented on src/main/java/pages/InventoryItemPage.java
> +    public void setCartPage() {
добавить отступ перед методом

2021-11-03 16:25 UTC, vchesnakoutest commented on src/main/java/pages/LoginPage.java
> +    public String errorMessagePassword() {
изменить название метода

2021-11-03 16:25 UTC, vchesnakoutest commented on src/main/java/pages/LoginPage.java
> +        return driver.findElement(By.xpath("//*[@id=\"login_button_container\"]/div/form/div[3]/h3")).getText();
"//*[@id=\"login_button_container\"]/div/form/div[3]/h3" - не стабильный локатор

2021-11-03 16:25 UTC, vchesnakoutest commented on src/main/java/pages/LoginPage.java
> +    public String errorMessageEmptyFields() {
изменить название метода

2021-11-03 16:25 UTC, vchesnakoutest commented on src/main/java/pages/LoginPage.java
> +        return driver.findElement(By.xpath("//*[@id=\"login_button_container\"]/div/form/div[3]/h3/text()")).getText();
не стабильный локатор

2021-11-03 16:25 UTC, vchesnakoutest commented on src/test/java/tests/LoginPage.java
> +    }
в этих тестах не хватает ассертов

2021-11-08 00:19 UTC, vitalik33811 commented on src/test/java/tests/LoginPage.java
> +    }
Зачем тут ассерты?
В этом месте просто вводится имя пользователя и пароль, затем нажимается кнопка "вход".

2021-11-10 20:56 UTC, vchesnakoutest requested changes

2021-11-10 20:56 UTC, vchesnakoutest commented on src/main/java/pages/CheckoutStepTwoPage.java
> +    public void clickCheckoutFinishButton(){
добавляй отступ перед методом

2021-11-10 20:56 UTC, vchesnakoutest commented on src/main/java/pages/LoginPage.java
> +    public String logindErrorMessage() {
getLoginErrorMessageText

2021-11-10 20:56 UTC, vchesnakoutest commented on src/main/java/pages/LoginPage.java
> +    public String passwordErrorMessage() {
getPasswordErrorMessage

2021-11-14 14:35 UTC, merged